[project]
name = "class-06-why-to-adopt-openai-agents-sdk-introduction-to-mcps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
